# Header
menu:
  Home: /
  about: /about
  Archives: /archives
  Tags: /tags
  Categories: /categories
  Github:
    url: https://github.com/sulenn/sulenn.github.io
    icon: github

# Title on top left of menu. Leave empty to use main blog title
menu_title: qiubing

# URL of the Home page image
index_cover: /img/5.jpg

# 归档页面的封面
archives_cover: /img/10.jpg

# Default post title
default_post_title: Untitled

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname:
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics:

# Addthis ID
addthis:

# set your own favicon
favicon: /img/favicon.ico

# Social Accounts
twitter_url:
twitter_handle:
facebook_url:
github_url: https://github.com/sulenn/sulenn.github.io
weibo_url: https://weibo.com/u/5649728079
gitlab_url:
linkedin_url:
mailto: 273409891@qq.com